alter table ARHIDOC_PROIECT_ARHITECTURA drop column PROIECTANT_NUME cascade ;
alter table ARHIDOC_PROIECT_ARHITECTURA drop column PROIECTANT_ADRESA cascade ;
alter table ARHIDOC_PROIECT_ARHITECTURA drop column PROIECTANT_TELEFON cascade ;
